require:
  - rubocop-performance
  # - rubocop-rails
  # - rubocop-minitest

Style/StringLiterals:
  Description: "Checks if uses of quotes match the configured preference."
  StyleGuide: "https://github.com/bbatsov/ruby-style-guide#consistent-string-literals"
  EnforcedStyle: double_quotes
  Enabled: true

Style/Documentation:
  Description: "Document classes and non-namespace modules."
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false
